name: CI/CD for C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: "3.21.3"

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test
        run: |
          cd build
          ctest
